server:
  port: 8766
spring:
  application:
    name: provider-user-service-feign
eureka:
  instance:
    hostname: localost
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
feign:
  hystrix:
    enabled: true